repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: forbid-new-submodules
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.14.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-e", "SC2211"]
  - id: shfmt
    stages: [commit]
    args: ["-s", "-i", "2"]
  - id: script-must-have-extension
    stages: [commit]
